title: Alcides Pollazzon
description: Estudante de Ciência da Computação com formação em redes de computadores, fundamentos de cibersegurança, conhecimento em controles de proteção e políticas de segurança. Meu objetivo é atuar em operações Red Team / Red Ops.
body: H3LL0_W04LD !!!
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
show_downloads: true
# google_analytics: [add ID]

gem "github-pages", group: :jekyll_plugins


