title: AOPS Git Repository
description: Estudante de Ciência da Computação com formação em redes de computadores, fundamentos de cibersegurança e conhecimento em controles de proteção, incluindo firewalls, IDS/IPS, VPNs e políticas de segurança. Meu objetivo é atuar em operações ofensivas (Red Team / Red Ops).
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
