"""Snort IDS configuration generator — byte-compatible with BLK7ARCHv1_0.sh output."""

from __future__ import annotations

from pathlib import Path

from blk7rch.config.schema import BLK7Config
from blk7rch.utils.logger import log
from blk7rch.utils.run import chroot_run


class IDSSnortConfig:
    """Generates Snort configuration files inside the installed system.

    Produces files identical to those generated by ``BLK7ARCHv1_0.sh``:

    * ``/etc/snort/snort.conf`` — main config (HOME_NET, alert_fast, includes)
    * ``/etc/snort/threshold.conf`` — (empty by default, present for include)
    * ``/etc/snort/suppress.conf`` — minimal suppress stubs
    * ``/etc/snort/rules/local.rules`` — SSH brute-force + ICMP flood rules;
      RDP rule added when profile is ``strict``.

    Parameters
    ----------
    target:
        Mount point of the installed system.
    cfg:
        BLK7 configuration instance.
    dry_run:
        When *True*, file writes and chroot commands are skipped.
    """

    def __init__(self, target: Path, cfg: BLK7Config, dry_run: bool = False) -> None:
        """Initialise the generator."""
        self.target = target
        self.cfg = cfg
        self.dry_run = dry_run
        self._snort_dir = target / "etc" / "snort"
        self._rules_dir = self._snort_dir / "rules"

    def install(self) -> None:
        """Write all Snort configuration files and validate the config.

        Raises
        ------
        RuntimeError
            If ``snort -T`` exits with a non-zero code.
        """
        log.step("Snort: writing configuration files")

        if not self.dry_run:
            self._rules_dir.mkdir(parents=True, exist_ok=True)

        self._write_snort_conf()
        self._write_threshold_conf()
        self._write_suppress_conf()
        self._write_local_rules()
        self._validate()

        log.ok("Snort: configuration complete")

    def _write(self, path: Path, content: str) -> None:
        """Write *content* to *path* (no-op in dry-run mode)."""
        if self.dry_run:
            log.dry(f"write {path}")
            return
        path.write_text(content)

    def _write_snort_conf(self) -> None:
        """Write ``/etc/snort/snort.conf``."""
        content = (
            f"# Precision-focused Snort profile generated by BLK7rch v1.0.0\n"
            f"var HOME_NET {self.cfg.ids_home_net}\n"
            f"var EXTERNAL_NET !$HOME_NET\n"
            f"config policy_mode: tap\n"
            f"config alert_with_interface_name\n"
            f"output alert_fast: /var/log/snort/alert.fast\n"
            f"include /etc/snort/threshold.conf\n"
            f"include /etc/snort/suppress.conf\n"
            f"include /etc/snort/rules/local.rules\n"
        )
        self._write(self._snort_dir / "snort.conf", content)

    def _write_threshold_conf(self) -> None:
        """Write ``/etc/snort/threshold.conf`` (empty placeholder)."""
        self._write(self._snort_dir / "threshold.conf", "# Snort threshold configuration\n")

    def _write_suppress_conf(self) -> None:
        """Write ``/etc/snort/suppress.conf`` with a commented example."""
        content = (
            "# Default suppressions — keep minimal to avoid hiding true positives.\n"
            "# suppress gen_id 1, sig_id 2000001, track by_src, ip 10.0.0.0/8\n"
        )
        self._write(self._snort_dir / "suppress.conf", content)

    def _write_local_rules(self) -> None:
        """Write ``/etc/snort/rules/local.rules`` (balanced + optional strict rules)."""
        rules = (
            'alert tcp any any -> $HOME_NET 22 (msg:"SNORT SSH brute-force"; '
            "flow:to_server,established; "
            "detection_filter:track by_src, count 12, seconds 60; sid:1000001; rev:1;)\n"
            'alert icmp any any -> $HOME_NET any (msg:"SNORT ICMP flood"; '
            "itype:8; "
            "detection_filter:track by_src, count 80, seconds 10; sid:1000002; rev:1;)\n"
        )

        if self.cfg.ids_snort_profile == "strict":
            rules += (
                'alert tcp any any -> $HOME_NET 3389 (msg:"SNORT RDP brute-force"; '
                "flow:to_server,established; "
                "detection_filter:track by_src, count 10, seconds 60; sid:1000003; rev:1;)\n"
            )

        self._write(self._rules_dir / "local.rules", rules)

    def _validate(self) -> None:
        """Run ``snort -T`` inside the chroot to validate the configuration."""
        log.info("Snort: validating configuration")
        chroot_run(
            self.target,
            ["snort", "-T", "-c", "/etc/snort/snort.conf"],
            dry_run=self.dry_run,
        )
        log.ok("Snort: configuration validated")
