#!/bin/bash 
[[ $# -ne 1 ]] && echo "Input Argument!" && exit 1
[[ -f $1 ]] && echo "Case Sensitive" && exit 1 
whrmi=$( pwd )
data=$( date +"%d/%m/%Y")
header="#!/bin/bash
#----------------------------------------------------------------------------
# Project	: $1
#----------------------------------------------------------------------------
# Date		: $data
#----------------------------------------------------------------------------
# WheremI	: $whrmi
#----------------------------------------------------------------------------
# CreatedBy	: ADVAN7 Offensive Security | https://github.com/Advan7Sapo
#----------------------------------------------------------------------------
"
clear
echo "$header" > $1
chmod 755 $1
micro $1
echo "Script $1 created successfully!"