"""Generated install artifacts for feature-specific runtime files."""

from __future__ import annotations

import os
from pathlib import Path

_IGNORED_PREFIXES = ("docker", "veth", "br-", "virbr", "podman", "cni", "flannel")


def _configured_interfaces() -> str:
    return os.environ.get("ADV7SEC_SURICATA_INTERFACES") or os.environ.get(
        "IPSIDS_SURICATA_INTERFACES",
        "",
    )


def detect_active_interfaces() -> str:
    """[FIX-UNIFIED-INSTALL] Detect active non-loopback interfaces for Suricata."""
    configured = _configured_interfaces()
    if configured:
        return configured
    candidates: list[str] = []
    for net_path in Path("/sys/class/net").glob("*"):
        name = net_path.name
        if name == "lo" or name.startswith(_IGNORED_PREFIXES):
            continue
        state = net_path / "operstate"
        if state.is_file() and state.read_text(encoding="utf-8").strip() == "up":
            candidates.append(name)
    return " ".join(sorted(candidates)) or "eth0"


def detect_target_home() -> Path:
    """[FIX-UNIFIED-INSTALL] Resolve target home for scoped user-facing configs."""
    configured = os.environ.get("ADV7SEC_TARGET_HOME") or os.environ.get("TARGET_HOME")
    if configured:
        return Path(configured)
    return Path(os.environ.get("HOME", "/home/user"))


def build_generated_artifacts(features: list[str]) -> dict[str, tuple[str, int]]:
    """[FIX-UNIFIED-INSTALL] Build derived config files for selected features."""
    artifacts: dict[str, tuple[str, int]] = {}
    if "suricata" in features:
        interfaces = detect_active_interfaces()
        artifacts["etc/default/ipsids-suricata"] = (
            f'SURICATA_INTERFACES="{interfaces}"\n',
            0o644,
        )
    if "clamav" in features:
        target_home = detect_target_home()
        artifacts["etc/clamav/clamd.d/99-openbox-scope.conf"] = (
            "# [FIX-UNIFIED-INSTALL] Generated by ADV7Sec 1.0\n"
            f"OnAccessIncludePath {target_home}/Downloads\n"
            "OnAccessIncludePath /tmp\n"
            "OnAccessIncludePath /run/media\n"
            "OnAccessMaxFileSize 20M\n"
            "OnAccessExcludeUname clamav\n"
            "OnAccessPrevention no\n",
            0o644,
        )
        artifacts["etc/systemd/system/clamav-clamonacc.service.d/override.conf"] = (
            "[Service]\n"
            "ExecStart=\n"
            "ExecStart=/usr/bin/clamonacc -F --fdpass --log=/var/log/clamav/clamonacc.log\n",
            0o644,
        )
    return artifacts


def write_generated_artifacts(root_dir: Path, features: list[str]) -> list[Path]:
    """[FIX-UNIFIED-INSTALL] Materialize generated files into the target root."""
    written: list[Path] = []
    for relative_path, (content, mode) in build_generated_artifacts(features).items():
        target_path = root_dir / relative_path
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(content, encoding="utf-8")
        target_path.chmod(mode)
        written.append(target_path)
    return written
